# server
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:

  # 자동 재부팅
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: lumen
    password: 150321
    driver-class-name: org.postgresql.Driver

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: com.lumen-prototype.www.config.CustomNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

file:
  upload-dir: C:\\lumen\\upload\\
  baseUrl: http://localhost:8081/files/video/

ffmpeg:
  path: "C:\\Program Files (x86)\\ffmpegyag\\bin"

java:
  path: "C:\\lumen\\jdk-17\\bin"