# server
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:

  # 자동 재부팅
  main:
    allow-bean-definition-overriding: true


  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: lumen
    password: 150321
    driver-class-name: org.postgresql.Driver

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: com.lumen-prototype.www.config.CustomNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

file:
  upload-dir: C:\\lumen\\upload\\